default_stage:
  default_modifiers:
    GPTQModifier:
      targets: [Linear]
      ignore: [lm_head, 're:.*visual.*', model.language_model.layers.0.linear_attn.in_proj_b,
        model.language_model.layers.0.linear_attn.in_proj_a, model.language_model.layers.1.linear_attn.in_proj_b,
        model.language_model.layers.1.linear_attn.in_proj_a, model.language_model.layers.2.linear_attn.in_proj_b,
        model.language_model.layers.2.linear_attn.in_proj_a, model.language_model.layers.4.linear_attn.in_proj_b,
        model.language_model.layers.4.linear_attn.in_proj_a, model.language_model.layers.5.linear_attn.in_proj_b,
        model.language_model.layers.5.linear_attn.in_proj_a, model.language_model.layers.6.linear_attn.in_proj_b,
        model.language_model.layers.6.linear_attn.in_proj_a, model.language_model.layers.8.linear_attn.in_proj_b,
        model.language_model.layers.8.linear_attn.in_proj_a, model.language_model.layers.9.linear_attn.in_proj_b,
        model.language_model.layers.9.linear_attn.in_proj_a, model.language_model.layers.10.linear_attn.in_proj_b,
        model.language_model.layers.10.linear_attn.in_proj_a, model.language_model.layers.12.linear_attn.in_proj_b,
        model.language_model.layers.12.linear_attn.in_proj_a, model.language_model.layers.13.linear_attn.in_proj_b,
        model.language_model.layers.13.linear_attn.in_proj_a, model.language_model.layers.14.linear_attn.in_proj_b,
        model.language_model.layers.14.linear_attn.in_proj_a, model.language_model.layers.16.linear_attn.in_proj_b,
        model.language_model.layers.16.linear_attn.in_proj_a, model.language_model.layers.17.linear_attn.in_proj_b,
        model.language_model.layers.17.linear_attn.in_proj_a, model.language_model.layers.18.linear_attn.in_proj_b,
        model.language_model.layers.18.linear_attn.in_proj_a, model.language_model.layers.20.linear_attn.in_proj_b,
        model.language_model.layers.20.linear_attn.in_proj_a, model.language_model.layers.21.linear_attn.in_proj_b,
        model.language_model.layers.21.linear_attn.in_proj_a, model.language_model.layers.22.linear_attn.in_proj_b,
        model.language_model.layers.22.linear_attn.in_proj_a]
      scheme: W4A16
      bypass_divisibility_checks: false
      requires_calibration_data: true
      block_size: 128
      dampening_frac: 0.01
      actorder: static
      batched_quantization: auto
